---
# tasks file for nginx-php-fpm_role


- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Install PHP-FPM
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "php{{ php_version }}"
    - "php{{ php_version }}-fpm"

- name: Prepare port 80
  include_tasks:
    file: port_80.yml
  when: nginx_port == "80"

- name: Update FPM Configuration
  ansible.builtin.lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    regexp: "^listen ="
    line: "listen = {{ tcp_socket | default(unix_socket) }}"
  notify: Restart php-fpm

- name: Copy website files to the server's document root
  ansible.builtin.copy:
    src: files/index.php
    dest: "{{ nginx_document_root }}"
    mode: preserve

- name: Apply Nginx template
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart nginx

- name: Enable new site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Restart nginx

- name: Ensure nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
